### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by lansas** [sampetrosov/SignaturePrinter#2]
window.printText("\nMustafa\nKemal\n\n\n\n",function(){
                alert("it is printed");    
            });

how can I set font size in that function? Is it possible?

**Comment by sampetrosov** [comment]
@lansas which model of bluetooth printer do you use? For example printers with ESC/POS support \x1b\x21\x00 escape characters for Big Font. You should look that in the documentation of the printer that you use.

**Comment by lansas** [comment]
it supports but I dont undesrtand how to use that characters in code

**Comment by sampetrosov** [comment]
@lansas  you can just write the escape sequence before the text you need to be printed otherwise:
for example: 
In this 2 cases former will print big font and the latter small.
window.printText("\x1b\x21\x00 Big Font \r\n",function(){
            alert("it is printed");    
        });

window.printText("\x1b\x21\x01 Small Font \r\n",function(){
            alert("it is printed");    
        });

But you need to be careful as when you set escape sequence printer will work with that one until you change it to another one.
